import { expect,it } from 'vitest';
import { createDraft, type GenerationDependencies } from './generation-service';
const input={prompt:'The timer is stuck',location:'Dorm laundry',language:'en' as const};
function fixture(fail=false){const state:{reserved:boolean;released:boolean;saved:unknown[]}={reserved:false,released:false,saved:[]};const deps:GenerationDependencies={configured:true,reserve:async()=>{state.reserved=true;return 'token';},release:async()=>{state.released=true;},generate:async()=>{if(fail)throw new Error('upstream');return {title:'Timer fiction',body:'One minute took half an hour.',model:'test-model',systemPrompt:'system'};},save:async(data)=>{state.saved.push(data);return '44444444-4444-4444-8444-444444444444';}};return{state,deps};}
it('denies an anonymous generation without reserving quota',async()=>{const {state,deps}=fixture();await expect(createDraft(null,input,deps)).rejects.toThrow('signInRequired');expect(state.reserved).toBe(false);});
it('reports missing configuration before calling provider or quota',async()=>{const {state,deps}=fixture();deps.configured=false;await expect(createDraft('user',input,deps)).rejects.toThrow('aiUnavailable');expect(state.reserved).toBe(false);});
it('persists original prompt, result and provenance before returning an editable draft',async()=>{const {state,deps}=fixture();expect(await createDraft('user',input,deps)).toEqual({generationId:'44444444-4444-4444-8444-444444444444',title:'Timer fiction',body:'One minute took half an hour.'});expect(state.saved).toEqual([{userId:'user',token:'token',prompt:'The timer is stuck',location:'Dorm laundry',language:'en',title:'Timer fiction',body:'One minute took half an hour.',model:'test-model',systemPrompt:'system'}]);});
it('releases the reservation after upstream failure and returns a safe error',async()=>{const {state,deps}=fixture(true);await expect(createDraft('user',input,deps)).rejects.toThrow('aiFailed');expect(state.released).toBe(true);expect(state.saved).toEqual([]);});
it('rejects malformed or oversized model text before saving and releases quota',async()=>{const {state,deps}=fixture();deps.generate=async()=>({title:'',body:'a'.repeat(3001),model:'model',systemPrompt:'system'});await expect(createDraft('user',input,deps)).rejects.toThrow('aiFailed');expect(state.saved).toEqual([]);expect(state.released).toBe(true);});
it('releases the reservation when persistence fails',async()=>{const {state,deps}=fixture();deps.save=async()=>{throw new Error('database');};await expect(createDraft('user',input,deps)).rejects.toThrow('aiFailed');expect(state.released).toBe(true);});
