import {expect,it,vi} from 'vitest';
import {createDraft,type GenerationDependencies,type DraftInput} from './generation-service';
const input={prompt:'The cat waits at the washing machine',location:'Dorm laundry',language:'en' as const,breed:'tabby' as const,style:'illustration' as const};
const image=new Uint8Array(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a3ioAAAAASUVORK5CYII=','base64'));
function fixture(){const state={reserved:false,released:false,removed:false,saved:[] as unknown[]};const deps:GenerationDependencies={configured:true,reserve:async()=>{state.reserved=true;return 'token';},release:async()=>{state.released=true;},generate:async()=>({image,mimeType:'image/png',model:'test-image',systemPrompt:'cat system'}),upload:async()=> 'user/image.png',remove:async()=>{state.removed=true;},preview:async()=> 'https://storage.example/signed/image.png',save:async data=>{state.saved.push(data);return '44444444-4444-4444-8444-444444444444';}};return{state,deps};}
it('denies visitors without reserving quota',async()=>{const {state,deps}=fixture();await expect(createDraft(null,input,deps)).rejects.toThrow('signInRequired');expect(state.reserved).toBe(false);});
it('reports disabled image generation before any external work',async()=>{const {state,deps}=fixture();deps.configured=false;await expect(createDraft('user',input,deps)).rejects.toThrow('aiUnavailable');expect(state.reserved).toBe(false);});
it('stores private image and original prompt before returning the preview',async()=>{const{state,deps}=fixture();expect(await createDraft('user',input,deps)).toEqual({generationId:'44444444-4444-4444-8444-444444444444',imageUrl:'https://storage.example/signed/image.png'});expect(state.saved).toEqual([{...input,userId:'user',token:'token',imagePath:'user/image.png',mimeType:'image/png',model:'test-image',systemPrompt:'cat system'}]);});
it('rejects unknown cat options before reserving quota',async()=>{const{state,deps}=fixture();await expect(createDraft('user',{...input,breed:'dog'} as unknown as DraftInput,deps)).rejects.toThrow('invalidText');expect(state.reserved).toBe(false);});
it('rejects disguised or oversized image output and releases quota',async()=>{for(const image of [new Uint8Array([1,2,3]),new Uint8Array(5242881)]){const{state,deps}=fixture();deps.generate=async()=>({image,mimeType:'image/png',model:'test',systemPrompt:'cat'});await expect(createDraft('user',input,deps)).rejects.toThrow('aiFailed');expect(state.released).toBe(true);expect(state.saved).toEqual([]);}});
it('removes the uploaded draft if persistence fails, and releases quota',async()=>{const{state,deps}=fixture();deps.save=async()=>{throw new Error('db');};await expect(createDraft('user',input,deps)).rejects.toThrow('aiFailed');expect(state.removed).toBe(true);expect(state.released).toBe(true);});
it('releases quota after an upstream failure and emits no prompt or secret',async()=>{const{state,deps}=fixture();deps.generate=async()=>{throw new Error('Gemini HTTP 503');};const log=vi.spyOn(console,'error').mockImplementation(()=>{});await expect(createDraft('user',input,deps)).rejects.toThrow('aiFailed');expect(state.released).toBe(true);expect(log).toHaveBeenCalledWith('AI image failure',{stage:'generate',status:'Gemini HTTP 503'});log.mockRestore();});
