'use client';
import Link from 'next/link';
import { useState,type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { useLanguage } from '../language-provider';
import { PhotoPicker } from '../photo-picker';
import { errorKey,type Language } from '@/src/lib/i18n';
import { publishRant } from '@/src/lib/rants/mutations';
import { createBrowserSupabaseClient } from '@/src/lib/supabase/browser';
export function RantForm(){
 const {t,language}=useLanguage();const router=useRouter();const [title,setTitle]=useState('');const [location,setLocation]=useState('');const [body,setBody]=useState('');const [photo,setPhoto]=useState<File|null>(null);const [prompt,setPrompt]=useState('');const [draftLanguage,setDraftLanguage]=useState<Language|null>(null);const [generationId,setGenerationId]=useState<string|null>(null);const [busy,setBusy]=useState<'publish'|'generate'|null>(null);const [error,setError]=useState<string|null>(null);
 async function publish(event:FormEvent){event.preventDefault();if(busy)return;setBusy('publish');setError(null);try{const result=await publishRant(createBrowserSupabaseClient(),{title,location,body,generationId},photo);router.push(`/rants/${result.id}`);router.refresh();}catch(e){setError(errorKey(e));setBusy(null);}}
 async function generate(){if(busy)return;setBusy('generate');setError(null);try{const response=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,location,language:draftLanguage??language})});const result=await response.json();if(!response.ok){setError(typeof result.error==='string'?result.error:'aiFailed');return;}setTitle(result.title);setBody(result.body);setGenerationId(result.generationId);}catch{setError('aiFailed');}finally{setBusy(null);}}
 return <main className="form-shell"><Link className="back-link" href="/">← {t('back')}</Link><header className="form-header"><p className="eyebrow">{t('newRant')}</p><h1>{t('formTitle')}</h1><p>{t('formIntro')}</p></header><form className="rant-form" onSubmit={publish}><div className="field"><label htmlFor="rant-title">{t('title')} <small>{[...title].length}/120</small></label><input id="rant-title" value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} required placeholder={t('titlePlaceholder')}/></div><div className="field"><label htmlFor="rant-location">{t('location')}</label><input id="rant-location" value={location} onChange={e=>setLocation(e.target.value)} maxLength={120} required placeholder={t('locationPlaceholder')}/></div><details className="ai-composer"><summary>✦ {t('aiTitle')}</summary><div><label htmlFor="ai-prompt">{t('aiPrompt')}</label><textarea id="ai-prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={3000} rows={3} placeholder={t('aiPromptPlaceholder')}/><div className="ai-actions"><label>{t('aiLanguage')}<select value={draftLanguage??language} onChange={e=>setDraftLanguage(e.target.value as Language)}><option value="en">English</option><option value="zh-CN">简体中文</option></select></label><button type="button" className="secondary" disabled={!!busy||!prompt.trim()||!location.trim()} onClick={generate}>{t(busy==='generate'?'generating':'generate')}</button></div><small>{t('aiHint')}</small></div></details><div className="field"><label htmlFor="rant-body">{t('body')} <small>{[...body].length}/3000</small></label><textarea id="rant-body" value={body} onChange={e=>setBody(e.target.value)} maxLength={3000} required rows={7} placeholder={t('bodyPlaceholder')}/></div>{generationId?<div className="ai-draft-status" role="status"><span>✦ {t('aiReady')}</span><button type="button" className="text-button" disabled={!!busy} onClick={()=>setGenerationId(null)}>{t('discardAi')}</button></div>:null}<PhotoPicker name="photo" onChange={setPhoto}/>{error?<p className="error-panel" role="alert">{t(error)}</p>:null}<div className="form-submit"><button disabled={!!busy} type="submit">{t(busy==='publish'?'publishing':'publish')} ↗</button></div></form></main>;
}
